apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "${{values.name}}.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "${{values.name}}.labels" . | nindent 4 }}
data:
  app.py: |
{{ .Files.Get "app.py" | indent 4 }}
  requirements.txt: |
{{ .Files.Get "requirements.txt" | indent 4 }}
  startup.sh: |
    #!/bin/bash
    set -e
    
    echo "Starting ${{values.name}} API service..."
    echo "Installing Python dependencies..."
    
    # Install dependencies
    pip install --no-cache-dir -r /app/requirements.txt
    
    # Set environment variables
    export SERVICE_NAME="${{values.name}}"
    export API_PORT="${{values.port}}"
    export ENVIRONMENT="production"
    export LOG_LEVEL="info"
    
    # Start the application
    echo "Starting Flask application on port ${{values.port}}..."
    cd /app && python app.py
