apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: database-service-template
  title: Database Service
  description: Create a service with PostgreSQL database backend
  tags:
    - service
    - database
    - postgresql
    - api
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/scaffolder-templates/database-service-template/template.yaml
spec:
  owner: development-team
  type: service
  parameters:
    - title: Service Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the service
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
          ui:help: 'Use lowercase letters, numbers, and hyphens only'
        description:
          title: Description
          type: string
          description: Brief description of the service
        owner:
          title: Owner
          type: string
          description: Owner of the service
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
        system:
          title: System
          type: string
          description: System this service belongs to
          default: demo-applications
          enum:
            - demo-applications
            - idp-platform
    - title: Database Configuration
      properties:
        dbName:
          title: Database Name
          type: string
          description: Name of the PostgreSQL database
          default: app_db
          pattern: '^[a-z0-9_]+$'
        dbUser:
          title: Database User
          type: string
          description: Database username
          default: app_user
          pattern: '^[a-z0-9_]+$'
        storageSize:
          title: Storage Size
          type: string
          description: Database storage size
          default: "2Gi"
          enum:
            - "1Gi"
            - "2Gi"
            - "5Gi"
            - "10Gi"
    - title: Service Configuration
      properties:
        port:
          title: Service Port
          type: integer
          description: Port for the service to listen on
          default: 8080
        replicas:
          title: Replicas
          type: integer
          description: Number of service replicas
          default: 2
          minimum: 1
          maximum: 5
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          dbName: ${{ parameters.dbName }}
          dbUser: ${{ parameters.dbUser }}
          storageSize: ${{ parameters.storageSize }}
          port: ${{ parameters.port }}
          replicas: ${{ parameters.replicas }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: publish
      name: Publish to GitHub
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Create new database service: ${{ parameters.name }}"
        branchName: create-${{ parameters.name }}
        description: |
          # New database service: ${{ parameters.name }}
          
          ${{ parameters.description }}
          
          This PR creates:
          - Service with PostgreSQL database
          - Helm chart with database dependency
          - ArgoCD application definition
          - Service catalog entry
          - Database secrets management
          
          Database: ${{ parameters.dbName }}
          Storage: ${{ parameters.storageSize }}
          
          Created by Backstage scaffolder.
        targetPath: .

    - id: register
      name: Register in Software Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/applications/${{ parameters.name }}/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
