apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "${{values.name}}.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;
        location / {
            root /etc/nginx/conf.d;
            index index.html;
        }
        location /health {
            return 200 '{"status":"healthy","service":"${{values.name}}"}';
            add_header Content-Type application/json;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>${{values.name}} - IDP Platform</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
            .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; }
            .header { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 20px; }
            .status { background: #27ae60; color: white; padding: 10px; border-radius: 4px; margin: 20px 0; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>${{values.name}}</h1>
                <p>${{values.description}}</p>
            </div>
            <div class="status">
                ✅ Service is running successfully via IDP Platform
            </div>
            <p>Generated by Backstage Scaffolder • Deployed via ArgoCD • Managed by Kubernetes</p>
        </div>
    </body>
    </html>
