apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "${{values.name}}.fullname" . }}
  labels:
    {{- include "${{values.name}}.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "${{values.name}}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Config checksum for auto-reloading (Phase 3)
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        # Secrets checksum for secret rotation
        {{- if .Values.externalSecrets.enabled }}
        secret-rotation-trigger: "v1" # manual trigger
        {{- end }}
      labels:
        {{- include "${{values.name}}.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.podSecurityContext.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- if .Values.externalSecrets.enabled }}
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.configSecretName }}
              key: API_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.configSecretName }}
              key: DATABASE_URL
        - name: DEBUG_MODE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.configSecretName }}
              key: DEBUG_MODE
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.credsSecretName }}
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecrets.credsSecretName }}
              key: PASSWORD
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 10 }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
        - name: var-cache-nginx
          mountPath: /var/cache/nginx
        - name: var-run
          mountPath: /var/run
        {{- if .Values.externalSecrets.enabled }}
        - name: secret-files
          mountPath: /etc/secrets
          readOnly: true
        {{- end }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "${{values.name}}.fullname" . }}-config
      - name: tmp-volume
        emptyDir: {}
      - name: var-cache-nginx
        emptyDir: {}
      - name: var-run
        emptyDir: {}
      {{- if .Values.externalSecrets.enabled }}
      - name: secret-files
        projected:
          sources:
          - secret:
              name: {{ .Values.externalSecrets.configSecretName }}
          - secret:
              name: {{ .Values.externalSecrets.credsSecretName }}
      {{- end }}
