apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-nginx
  namespace: demo-apps
  labels:
    app.kubernetes.io/name: demo-nginx
    app.kubernetes.io/component: webapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-nginx-secret-reader
  namespace: demo-apps
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-nginx-secret-reader
  namespace: demo-apps
subjects:
- kind: ServiceAccount
  name: demo-nginx
  namespace: demo-apps
roleRef:
  kind: Role
  name: demo-nginx-secret-reader
  apiGroup: rbac.authorization.k8s.io
