apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-nginx-config
  namespace: demo-apps
  annotations:
    argocd.argoproj.io/sync-options: "IgnoreExtraneous=true"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: demo-nginx-config-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        API_KEY: "{{ .api_key }}"
        DATABASE_URL: "{{ .database_url }}"
        DEBUG_MODE: "{{ .debug_mode }}"
  data:
  - secretKey: api_key
    remoteRef:
      key: demo-nginx/config
      property: api_key
  - secretKey: database_url
    remoteRef:
      key: demo-nginx/config
      property: database_url
  - secretKey: debug_mode
    remoteRef:
      key: demo-nginx/config
      property: debug_mode
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-nginx-creds
  namespace: demo-apps
  annotations:
    argocd.argoproj.io/sync-options: "IgnoreExtraneous=true"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: demo-nginx-creds-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        USERNAME: "{{ .username }}"
        PASSWORD: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      key: demo-nginx/creds
      property: username
  - secretKey: password
    remoteRef:
      key: demo-nginx/creds
      property: password
