apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Engineering Team
spec:
  type: team
  profile:
    displayName: Platform Team
    email: platform@idp-platform.local
    picture: https://api.dicebear.com/9.x/avataaars/svg?seed=Nolan&eyebrows=default,defaultNatural,flatNatural&eyes=default,happy&mouth=default,smile
  children: []
