apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: idp-platform
  description: Internal Developer Platform System
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
    backstage.io/managed-by-origin-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
spec:
  owner: platform-team
  domain: platform

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo-applications
  description: Demo applications for showcasing IDP capabilities
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
    backstage.io/managed-by-origin-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
spec:
  owner: development-team
  domain: applications

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Engineering Team
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
spec:
  type: team
  profile:
    displayName: Platform Team
    email: platform-team@idp-platform.local
    picture: https://avatars.githubusercontent.com/u/1?v=4
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development-team
  description: Application Development Team
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
spec:
  type: team
  profile:
    displayName: Development Team
    email: dev-team@idp-platform.local
    picture: https://avatars.githubusercontent.com/u/2?v=4
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: platform-admin
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
spec:
  profile:
    displayName: Platform Administrator
    email: admin@idp-platform.local
    picture: https://avatars.githubusercontent.com/u/3?v=4
  memberOf: [platform-team]

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: platform
  description: Platform infrastructure and tooling
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
spec:
  owner: platform-team

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: applications
  description: Business applications and services
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
spec:
  owner: development-team
