# File: applications/demo-apps/demo-nginx/catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-nginx
  description: Demo NGINX application with secure defaults and GitOps deployment
  annotations:
    # GitHub repository
    github.com/project-slug: theWalia/idp-platform
    
    # ArgoCD application - scaffolder-created apps only
    argocd/app-name: demo-nginx
    argocd/app-namespace: argocd
    
    # Kubernetes deployment info - correct namespace
    backstage.io/kubernetes-id: demo-nginx
    backstage.io/kubernetes-namespace: demo-apps
    
    # Prometheus metrics
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace="demo-apps",pod=~"demo-nginx-.*"}
    
  labels:
    environment: development
    tier: frontend
    type: demo
  tags:
    - nginx
    - demo
    - security-hardened
    - gitops
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
  system: demo-applications
  providesApis:
    - demo-nginx-api
  dependsOn:
    - resource:vault-secrets
    - resource:external-secrets-operator
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-nginx-api
  description: Demo NGINX HTTP API endpoints
spec:
  type: openapi
  lifecycle: experimental
  owner: platform-team
  system: demo-applications
  definition: |
    openapi: 3.0.0
    info:
      title: Demo NGINX API
      version: 1.0.0
      description: Demo application endpoints
    servers:
      - url: http://demo-nginx.demo-apps.svc.cluster.local
    paths:
      /health:
        get:
          summary: Health check endpoint
          responses:
            '200':
              description: Service is healthy
      /info:
        get:
          summary: Application info
          responses:
            '200':
              description: Application information
      /vault-status:
        get:
          summary: Vault connection status
          responses:
            '200':
              description: Vault connectivity status
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vault-secrets
  description: Vault-managed secrets for demo applications
spec:
  type: database
  owner: platform-team
  system: idp-platform
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: external-secrets-operator
  description: External Secrets Operator for secret synchronization
spec:
  type: service
  owner: platform-team
  system: idp-platform
