{{- if eq .Release.Name "backstage-platform" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      volumes:
        - name: backstage-cache
          hostPath:
            path: /var/lib/backstage-cache
            type: DirectoryOrCreate
      containers:
        - name: backstage
          volumeMounts:
            - name: backstage-cache
              mountPath: /opt/app-root/src/.cache
{{- end }}

