apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-github-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "backstage.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: backstage-github-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: {{ include "backstage.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
      data:
        github-token: "{{ "{{" }} .githubToken {{ "}}" }}"
        auth-github-client-id: "{{ "{{" }} .authGithubClientId {{ "}}" }}"
        auth-github-client-secret: "{{ "{{" }} .authGithubClientSecret {{ "}}" }}"
  data:
    - secretKey: githubToken
      remoteRef:
        key: backstage/github
        property: token
    - secretKey: authGithubClientId
      remoteRef:
        key: backstage/github
        property: client-id
    - secretKey: authGithubClientSecret
      remoteRef:
        key: backstage/github
        property: client-secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-db-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "backstage.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: backstage-db-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: {{ include "backstage.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
      data:
        postgres-password: "{{ "{{" }} .postgresPassword {{ "}}" }}"
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: backstage/database
        property: postgres-password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-argocd-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "backstage.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: backstage-argocd-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: {{ include "backstage.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
      data:
        argocd-token: "{{ "{{" }} .argocdToken {{ "}}" }}"
        argocd-password: "{{ "{{" }} .argocdPassword {{ "}}" }}"
  data:
    - secretKey: argocdToken
      remoteRef:
        key: backstage/argocd
        property: token
    - secretKey: argocdPassword
      remoteRef:
        key: backstage/argocd
        property: password
