apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: idp-platform
data:
  app-config.production.yaml: |
    app:
      title: IDP Platform - Backstage
      baseUrl: http://localhost:7007
      support:
        url: https://github.com/theWalia/idp-platform
        items:
          - title: Issues
            icon: github
            links:
              - url: https://github.com/theWalia/idp-platform/issues
                title: GitHub Issues

    organization:
      name: IDP Platform

    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
        host: 0.0.0.0
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: http://localhost:7007
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          database: backstage
          ssl: false
      cache:
        store: memory

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    techdocs:
      builder: 'local'
      generator:
        runIn: 'local'
      publisher:
        type: 'local'

    scaffolder:
      defaultAuthor:
        name: IDP Platform
        email: idp@example.com
      defaultCommitMessage: 'Initial commit from Backstage scaffolder'

    catalog:
      readonly: false
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location, Group, Template]
      locations:
        - type: url
          target: https://github.com/theWalia/idp-platform/blob/main/applications/demo-apps/demo-nginx/catalog-info.yaml
        - type: url
          target: https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/groups.yaml
        - type: url
          target: https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/catalog/systems.yaml
        # Scaffolder templates
        - type: url
          target: https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/templates/simple-web-app/template.yaml
        - type: url
          target: https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/templates/simple-api-service/template.yaml
        # Auto-discovery for generated apps
        - type: github-discovery
          target: https://github.com/theWalia/idp-platform/blob/main/applications/demo-apps/*/catalog-info.yaml
        
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - url: https://kubernetes.default.svc
              name: local-cluster
              authProvider: 'serviceAccount'
              skipTLSVerify: true
              skipMetricsLookup: false

    # ArgoCD Integration
    argocd:
      username: admin
      password: ${ARGOCD_ADMIN_PASSWORD}
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: default
              url: http://argo-cd-argocd-server.argocd.svc.cluster.local
              username: admin
              password: ${ARGOCD_ADMIN_PASSWORD}

    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true

    permission:
      enabled: false

    proxy:
      '/argocd/api':
        target: http://argo-cd-argocd-server.argocd.svc.cluster.local/api/v1/
        changeOrigin: true
        secure: false
        headers:
          Cookie: ${ARGOCD_AUTH_TOKEN}
