apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/managed-by: Helm
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: "secret"
      version: v2
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: backstage
          serviceAccountRef:
            name: backstage

