backstage:
  enabled: true

  image:
    registry: ghcr.io
    repository: backstage/backstage
    tag: "latest"
    pullPolicy: Always

  # Security configuration
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    seccompProfile:
      type: RuntimeDefault

  podSecurityContext:
    fsGroup: 1001
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    seccompProfile:
      type: RuntimeDefault

  # Resource allocation
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  # Storage configuration - hostPath for cache persistence
  extraVolumes:
    - name: backstage-cache
      hostPath:
        path: /var/lib/backstage-cache
        type: DirectoryOrCreate
    - name: app-config
      configMap:
        name: backstage-app-config

  extraVolumeMounts:
    - name: backstage-cache
      mountPath: /opt/app-root/src/.cache
    - name: app-config
      mountPath: /app/
      subPath: app-config.production.yaml
      readOnly: true

  # Environment variables from secrets
  extraEnvVars:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: backstage-github-secrets
          key: github-token
    - name: POSTGRES_HOST
      value: "backstage-postgresql"
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_USER
      value: "backstage"
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: backstage-db-secrets
          key: postgres-password

  # Service account configuration
  serviceAccount:
    create: true
    automountServiceAccountToken: false
    name: backstage
    annotations:
      app.kubernetes.io/managed-by: "Helm"

  service:
    type: ClusterIP

  # Ingress (disabled for now)
  ingress:
    enabled: false

  # PostgreSQL dependency
  postgresql:
    enabled: true
    auth:
      username: backstage
      database: backstage
      existingSecret: backstage-db-secrets
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: postgres-password
    primary:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: ""
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      securityContext:
        enabled: true
        fsGroup: 1001
        runAsUser: 1001
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

