apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-test.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-test.labels" . | nindent 4 }}
data:
  app.py: |
{{ .Files.Get "app.py" | indent 4 }}
  requirements.txt: |
{{ .Files.Get "requirements.txt" | indent 4 }}
  startup.sh: |
    #!/bin/bash
    set -e
    
    echo "Starting api-test API service..."
    echo "Installing Python dependencies..."
    
    # Install dependencies
    pip install --no-cache-dir -r /app/requirements.txt
    
    # Set environment variables
    export SERVICE_NAME="api-test"
    export API_PORT="8081"
    export ENVIRONMENT="production"
    export LOG_LEVEL="info"
    
    # Start the application
    echo "Starting Flask application on port 8081..."
    cd /app && python app.py
