apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-nginx.fullname" . }}
  labels:
    {{- include "demo-nginx.labels" . | nindent 4 }}
annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: {{ .Values.service.port }}
  prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo-nginx.selectorLabels" . | nindent 4 }}
