apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-website-template
  title: Simple Website
  description: Create a static website served by nginx
  tags:
    - website
    - static
    - nginx
    - frontend
  annotations:
    backstage.io/managed-by-location: url:https://github.com/theWalia/idp-platform/blob/main/infrastructure/backstage/scaffolder-templates/website-template/template.yaml
spec:
  owner: development-team
  type: website
  parameters:
    - title: Website Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the website
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
          ui:help: 'Use lowercase letters, numbers, and hyphens only'
        description:
          title: Description
          type: string
          description: Brief description of the website
        owner:
          title: Owner
          type: string
          description: Owner of the website
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
        system:
          title: System
          type: string
          description: System this website belongs to
          default: demo-applications
          enum:
            - demo-applications
            - idp-platform
    - title: Website Configuration
      properties:
        title:
          title: Website Title
          type: string
          description: Title to display on the website
          default: "My Website"
        theme:
          title: Theme
          type: string
          description: Color theme for the website
          default: blue
          enum:
            - blue
            - green
            - purple
            - red
        replicas:
          title: Replicas
          type: integer
          description: Number of replicas to run
          default: 2
          minimum: 1
          maximum: 5
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          title: ${{ parameters.title }}
          theme: ${{ parameters.theme }}
          replicas: ${{ parameters.replicas }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: publish
      name: Publish to GitHub
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Create new website: ${{ parameters.name }}"
        branchName: create-${{ parameters.name }}
        description: |
          # New website: ${{ parameters.name }}
          
          ${{ parameters.description }}
          
          This PR creates:
          - Static website with nginx
          - Helm chart for deployment
          - ArgoCD application definition
          - Service catalog entry
          
          Created by Backstage scaffolder.
        targetPath: .

    - id: register
      name: Register in Software Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/applications/${{ parameters.name }}/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
